[dependencies]
base = "0.14.9"
new-base = "0.4.0"
vector = "0.4.1"
promtracker = "https://github.com/research-ag/promtracker.git#main"
stable-trie = "0.0.1"

[dev-dependencies]
test = "2.0.0"

[toolchain]
moc = "0.14.9"