[dependencies]
base = "0.14.13"
core = "1.0.0"
vector = "0.4.1"
promtracker = "https://github.com/research-ag/promtracker.git#e3cbfb50113b637ab7c4a4c6e0f3dbaa0c707ffd"
stable-trie = "0.0.2"
stable-log-lists = "https://github.com/research-ag/stable-log-lists.git#30cba613fdcf7a459b53f5223198fdef832d81b1"

[dev-dependencies]
test = "2.0.0"

[toolchain]
moc = "0.14.13"
wasmtime = "42.0.0"