[package]
name = ""
version = "0.0.1"
description = ""
repository = "https://github.com/research-ag/hash-history-tracker"
keywords = [ ]
license = "Apache-2.0"

[dependencies]
base = "https://github.com/dfinity/motoko-base"
vector = "0.3.1"

[dev-dependencies]
test = "2.0.0"

[toolchain]
moc = "0.11.1"
wasmtime = "20.0.2"